name: The GIRD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d19571'
    - '#5f3c28'
    - '#9a573d'
    - '#fac78e'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
